packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@biomejs/biome': true
  '@swc/core': true
  esbuild: true
  nextra-theme-docs: true
  sharp: true
patchedDependencies:
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
