import { Project } from "ts-morph";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { glob } from "glob";
import path from "path";

async function sync() {
  const project = new Project();

  // 1. Freshly scan all component directories
  const scanPatterns = [
    "src/components/ui/**/*.tsx",
    "src/widgets/**/*.tsx",
    "src/app/(app)/chats/components/**/*.tsx",
    "src/app/(app)/dashboard/channels/components/**/*.tsx",
    "src/app/(app)/dashboard/demand/components/**/*.tsx",
    "src/app/(app)/dashboard/room-types/components/**/*.tsx",
    "src/app/(app)/dashboard/segments/components/**/*.tsx",
  ];

  const componentFiles = [
    ...new Set(
      (
        await Promise.all(
          scanPatterns.map((pattern) =>
            glob(pattern, {
              nodir: true,
              ignore: [
                "**/*.d.ts",
                "**/*.test.tsx",
                "**/*.spec.tsx",
                "**/*.stories.tsx",
                "**/node_modules/**",
              ],
              windowsPathsNoEscape: true,
            })
          )
        )
      ).flat()
    ),
  ];

  const definitions: string[] = [];
  const imports: string[] = [];
  const processedNames = new Set<string>();

  if (!existsSync("lib/ui-builder/registry")) {
    await mkdir("lib/ui-builder/registry", { recursive: true });
  }

  console.log(`Found ${componentFiles.length} component files`);

  for (const file of componentFiles) {
    if (!existsSync(file)) {
      console.log(`Skipping non-existent file: ${file}`);
      continue;
    }

    const fileName = path.basename(file, ".tsx");

    if (["index", "utils", "types", "schema"].includes(fileName)) {
      continue;
    }

    const pascalName = fileName
      .split(/[-_]/)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("");

    const sourceFile = project.addSourceFileAtPath(file);
    const exportedDeclarations = sourceFile.getExportedDeclarations();

    const isNamedExport = exportedDeclarations.has(pascalName);
    const hasDefaultExport = exportedDeclarations.has("default");

    if (!isNamedExport && !hasDefaultExport) {
      continue;
    }

    if (processedNames.has(pascalName)) {
      console.warn(`Skipping duplicate component name: ${pascalName} from ${file}`);
      continue;
    }

    processedNames.add(pascalName);

    const importPath =
      "@/" +
      file
        .replace(/^src[\\/]/, "")
        .replace(/\.tsx$/, "")
        .replace(/\\/g, "/");

    const importLine = isNamedExport
      ? `import { ${pascalName} } from "${importPath}";`
      : `import ${pascalName} from "${importPath}";`;

    imports.push(importLine);

    definitions.push(`
  ${pascalName}: {
    component: ${pascalName},
    schema: z.object({
      className: z.string().optional(),
    }),
    from: "${importPath}",
  }`);
  }

  const content = `/* eslint-disable @typescript-eslint/no-explicit-any */
import { z } from "zod";
${imports.join("\n")}

export const autoGeneratedDefinitions: Record<string, any> = {
${definitions.join(",\n")}
};`;

  await writeFile("lib/ui-builder/registry/auto-generated.ts", content);
  console.log(`✅ Success! Synced ${processedNames.size} components. Any missing files were ignored.`);
}

sync().catch((err) => {
  console.error(err);
  process.exit(1);
});