import { DuckDbProviderWrapper } from './duckdb-provider-wrapper';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <DuckDbProviderWrapper>
          {children}
        </DuckDbProviderWrapper>
      </body>
    </html>
  )
}

