import type { DataLibraryTableDefinition } from "./data-library_types"

export const dataLibraryRegistry: DataLibraryTableDefinition[] = [
  {
    key: "metrics_core.lkp_segment",
    displayName: "Segment Lookup",
    description: "Standard segment classification definitions and codes.",
    tableType: "lookup",
    category: "Segment",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "lkp_segment",
    primaryKey: "rawCode",
    columns: [
      { name: "rawCode", label: "Segment Code", type: "code", editable: true, required: true },
      { name: "rawName", label: "Segment Name", type: "string", editable: true, required: true },
      { name: "mappedValue", label: "Category", type: "string", editable: true },
      { name: "mappedGroup", label: "Group", type: "string", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
      { name: "notes", label: "Notes", type: "string", editable: true },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: false,
    requiredPermissions: {
      view: "metrics.lookup.view",
      edit: "metrics.lookup.edit",
      publish: "metrics.lookup.publish",
    },
  },
  {
    key: "metrics_core.map_segment",
    displayName: "Segment Mapping",
    description: "Source PMS segment codes mapped to standard metrics_core segment definitions.",
    tableType: "mapping",
    category: "Segment",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "map_segment",
    primaryKey: "id",
    lookupTableDependencies: ["metrics_core.lkp_segment"],
    columns: [
      { name: "sourceSystem", label: "Source System", type: "badge", required: true },
      { name: "rawCode", label: "Source Code", type: "code", required: true },
      { name: "rawName", label: "Source Description", type: "string" },
      { name: "mappedCode", label: "Target Segment", type: "code", editable: true },
      { name: "mappedValue", label: "Canonical Name", type: "string" },
      { name: "status", label: "Mapping Status", type: "status" },
      { name: "confidence", label: "Confidence", type: "number" },
      { name: "reviewReason", label: "Review Reason", type: "string" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: true,
    requiredPermissions: {
      view: "metrics.mapping.view",
      edit: "metrics.mapping.edit",
      publish: "metrics.mapping.publish",
    },
  },
  {
    key: "metrics_core.lkp_channel",
    displayName: "Channel Lookup",
    description: "Governed channel taxonomy and distribution definitions.",
    tableType: "lookup",
    category: "Channel",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "lkp_channel",
    primaryKey: "rawCode",
    columns: [
      { name: "rawCode", label: "Channel Code", type: "code", editable: true, required: true },
      { name: "rawName", label: "Channel Name", type: "string", editable: true, required: true },
      { name: "mappedValue", label: "Category", type: "string", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: false,
    requiredPermissions: {
      view: "metrics.lookup.view",
      edit: "metrics.lookup.edit",
      publish: "metrics.lookup.publish",
    },
  },
  {
    key: "metrics_core.map_channel",
    displayName: "Channel Mapping",
    description: "Source channel codes mapped to standard channel taxonomy.",
    tableType: "mapping",
    category: "Channel",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "map_channel",
    primaryKey: "id",
    lookupTableDependencies: ["metrics_core.lkp_channel"],
    columns: [
      { name: "sourceSystem", label: "Source System", type: "badge" },
      { name: "rawCode", label: "Source Code", type: "code" },
      { name: "rawName", label: "Source Description", type: "string" },
      { name: "mappedCode", label: "Target Channel", type: "code", editable: true },
      { name: "mappedValue", label: "Canonical Name", type: "string" },
      { name: "status", label: "Status", type: "status" },
      { name: "confidence", label: "Confidence", type: "number" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: true,
    requiredPermissions: {
      view: "metrics.mapping.view",
      edit: "metrics.mapping.edit",
      publish: "metrics.mapping.publish",
    },
  },
  {
    key: "metrics_core.map_roomtype",
    displayName: "Room Type Mapping",
    description: "Source room codes mapped to standard room categories.",
    tableType: "mapping",
    category: "Room Type",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "map_roomtype",
    primaryKey: "id",
    columns: [
      { name: "sourceSystem", label: "Source System", type: "badge" },
      { name: "rawCode", label: "Source Room Code", type: "code" },
      { name: "rawName", label: "Source Room Name", type: "string" },
      { name: "mappedCode", label: "Target Category", type: "code", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: true,
    requiredPermissions: {
      view: "metrics.mapping.view",
      edit: "metrics.mapping.edit",
      publish: "metrics.mapping.publish",
    },
  },
  {
    key: "metrics_core.map_source",
    displayName: "Source Mapping",
    description: "Source system codes mapped to canonical booking sources.",
    tableType: "mapping",
    category: "Source",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "map_source",
    primaryKey: "id",
    columns: [
      { name: "sourceSystem", label: "Source System", type: "badge" },
      { name: "rawCode", label: "Source Code", type: "code" },
      { name: "rawName", label: "Source Name", type: "string" },
      { name: "mappedCode", label: "Canonical Source", type: "code", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: true,
    requiredPermissions: {
      view: "metrics.mapping.view",
      edit: "metrics.mapping.edit",
      publish: "metrics.mapping.publish",
    },
  },
  {
    key: "metrics_core.map_market",
    displayName: "Market Mapping",
    description: "Geographic and feeder market mappings.",
    tableType: "mapping",
    category: "Market",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "map_market",
    primaryKey: "id",
    columns: [
      { name: "sourceSystem", label: "Source System", type: "badge" },
      { name: "rawCode", label: "Source Code", type: "code" },
      { name: "rawName", label: "Source Market", type: "string" },
      { name: "mappedCode", label: "Target Market", type: "code", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: true,
    requiredPermissions: {
      view: "metrics.mapping.view",
      edit: "metrics.mapping.edit",
      publish: "metrics.mapping.publish",
    },
  },
  {
    key: "metrics_core.map_rate",
    displayName: "Rate Mapping",
    description: "Rate code mappings to standard rate plans.",
    tableType: "mapping",
    category: "Rate",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "map_rate",
    primaryKey: "id",
    columns: [
      { name: "sourceSystem", label: "Source System", type: "badge" },
      { name: "rawCode", label: "Rate Code", type: "code" },
      { name: "rawName", label: "Rate Plan", type: "string" },
      { name: "mappedCode", label: "Target Rate Plan", type: "code", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: true,
    requiredPermissions: {
      view: "metrics.mapping.view",
      edit: "metrics.mapping.edit",
      publish: "metrics.mapping.publish",
    },
  },
  {
    key: "metrics_core.dim_property",
    displayName: "Property Dimension",
    description: "Governed property master dimension definitions.",
    tableType: "dimension",
    category: "Property",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "dim_property",
    primaryKey: "rawCode",
    columns: [
      { name: "rawCode", label: "Property ID", type: "code", editable: true, required: true },
      { name: "rawName", label: "Property Name", type: "string", editable: true, required: true },
      { name: "mappedValue", label: "Brand / Portfolio", type: "string", editable: true },
      { name: "status", label: "Status", type: "status" },
      { name: "updatedAt", label: "Updated At", type: "date" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: false,
    requiredPermissions: {
      view: "metrics.lookup.view",
      edit: "metrics.lookup.edit",
      publish: "metrics.lookup.publish",
    },
  },
  {
    key: "metrics_core.lkp_event_category",
    displayName: "Event Category Lookup",
    description: "Market event category definitions.",
    tableType: "lookup",
    category: "Event",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "lkp_event_category",
    primaryKey: "rawCode",
    columns: [
      { name: "rawCode", label: "Category Code", type: "code", editable: true },
      { name: "rawName", label: "Category Name", type: "string", editable: true },
      { name: "status", label: "Status", type: "status" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: false,
    requiredPermissions: {
      view: "metrics.lookup.view",
      edit: "metrics.lookup.edit",
      publish: "metrics.lookup.publish",
    },
  },
  {
    key: "metrics_core.lkp_event_impact",
    displayName: "Event Impact Lookup",
    description: "Market event impact classification levels.",
    tableType: "lookup",
    category: "Event",
    bigQueryDataset: "metrics_core",
    bigQueryTable: "lkp_event_impact",
    primaryKey: "rawCode",
    columns: [
      { name: "rawCode", label: "Impact Code", type: "code", editable: true },
      { name: "rawName", label: "Impact Severity", type: "string", editable: true },
      { name: "status", label: "Status", type: "status" },
    ],
    supportsDrafts: true,
    supportsPublish: true,
    supportsUnmappedQueue: false,
    requiredPermissions: {
      view: "metrics.lookup.view",
      edit: "metrics.lookup.edit",
      publish: "metrics.lookup.publish",
    },
  },
]

export function getDataLibraryTableDefinition(key: string): DataLibraryTableDefinition | undefined {
  return dataLibraryRegistry.find((def) => def.key === key)
}

export function listDataLibraryRegistryEntries(): DataLibraryTableDefinition[] {
  return [...dataLibraryRegistry]
}
